### ISSUE TITLE
Need blank registry when no components in repo

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Tooling-Windows-Submodule#22] opened 2023-03-15 17:12 UTC
Discovered from #2

You can't build the all-up sample without a component as it doesn't generate a document/sample registry required for the sample app code to build.

We need a dummy stub here to be generated from the generator even if there are no components...

**Comment by Arlodotexe** [comment] 2023-08-01 19:21
Just noticed #32 is a duplicate of this. Since we have a _lot_ of notes there, I'm closing this in favor of #32.

**Closed by Arlodotexe** 2023-08-01 19:21 UTC
Labels: sample app 🖼, source generator :gear:
